services:
  ybYaml:
    image: ybfeed:latest
    build: .
    environment:
      YBF_DATA_DIR: /data
      YBF_MAX_DATA_SIZE: ${YBF_MAX_DATA_SIZE:-10240}
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
